version: '3'

services:
    intect_cli:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "6006:6006"
            - "9000:9000"
        volumes:
            - .:/code:z
