version: '3'

services:
    intect:
        container_name: intect
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "6006:6006"
            - "9000:9000"
        volumes:
            - .:/code:z
        tty: True
